### ISSUE TITLE
Clean up unused imports.

### ISSUE THREAD

**Issue by VeKett** [GreenDiscord/TransHelper-Source#1]
Your code is full of unused imports that could be removed.
Most notably in your main.py (and remember that you don't have to import jishaku to use it as an extension)

Could also be worth noting that you left your Hypixel API key in the code

As seen as the bot is being used on Linux (could see from your eval in discord.py discord server) you could consider using environment variables so you don't risk exposing API keys or tokens.

**Comment by GreenDiscord** [comment]
Ok! Is there anything else?

**Comment by VeKett** [comment]
cogs does not need to be imported as a module, you aren't using threading or json in your main.py, and you imported os twice

**Comment by VeKett** [comment]
Note this problem exists in a bunch of your cogs too.
