### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by cyrus01337** [GreenDiscord/TransHelper-Source#5]
#4 was created with the sole purpose of reviewing and adding grammar changes, however a review would not be a review if changes were not made by the original author. Alongside this, all issues mentioned were also repeat offenses carried across all `.py` files and should definitely be addressed globally as opposed to only the listed files (as I had mistakenly organised).

The PR addresses a majority of the core problems and I will continue to list further issues as time comes.

**Comment by GreenDiscord** [comment]
So what should I do, change everything you did? Or take the things you have changed and the remember to keep them that way?

**Comment by cyrus01337** [comment]
That is your decision to make.
