### ISSUE TITLE
Action occurs when mentioned in message irrespective of content

### ISSUE THREAD

**Issue by cyrus01337** [GreenDiscord/TransHelper-Source#6]
## What went wrong
The bot assumes I am mentioning it to use it when this was not the original intention - this appears to apply to any message irrespective of whether the bot is being used as an argument in a command or simply being mentioned in a casual message.

![Preview](https://i.imgur.com/MZ2UDTA.png)

## How to reproduce
Send a message with any (or no content) preceding/following the bot's mention, by sending e.g.: `>>>test @TransHelper
#0711` or simply `TransHelper#0711 who's bot is this?`

**Comment by GreenDiscord** [comment]
Will be fixing soon!

**Comment by GreenDiscord** [comment]
Fixed it now!
